### ISSUE TITLE
Bespoke dataset properties

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#296] opened 2021-07-22 13:29 UTC
The trade.gss-data.org.uk portal made use of some extra properties to help describe datasets:

```
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://gss-data.org.uk/def/metadata/ontology> a owl:Ontology;
  dcterms:title "COGS metadata terms";
  rdfs:label "COGS metadata terms" .

<http://gss-data.org.uk/def/metadata/source> a rdf:Property;
  rdfs:isDefinedBy <http://gss-data.org.uk/def/metadata/ontology>;
  rdfs:label "Source" .

<http://gss-data.org.uk/def/metadata/status> a rdf:Property;
  rdfs:isDefinedBy <http://gss-data.org.uk/def/metadata/ontology>;
  rdfs:label "Status" .

<http://gss-data.org.uk/def/metadata/recommendedUsage> a rdf:Property;
  rdfs:isDefinedBy <http://gss-data.org.uk/def/metadata/ontology>;
  rdfs:label "Recommended usage" .

<http://gss-data.org.uk/def/metadata/strengths> a rdf:Property;
  rdfs:isDefinedBy <http://gss-data.org.uk/def/metadata/ontology>;
  rdfs:label "Strengths" .

<http://gss-data.org.uk/def/metadata/weaknesses> a rdf:Property;
  rdfs:isDefinedBy <http://gss-data.org.uk/def/metadata/ontology>;
  rdfs:label "Weaknesses" .
```

Further, the literal values of these properties can use the `markdown:Resource` datatype.

These properties should be added to the PMD Dataset metadata fields in https://github.com/GSS-Cogs/gss-utils/blob/master/gssutils/metadata/pmdcat.py#L43

**Comment by ajtucker** [comment] 2021-08-11 10:58
I have no recollection of writing this, but it almost duplicates #307 and is maybe a better way to deal with things so that we can write code like:

```
scraper.dataset.strengths = 'some strengths'
```

**Comment by canwaf** [comment] 2022-05-24 11:04
Duplicate of #307.

**Closed by canwaf** 2022-05-24 11:04 UTC
